server:
  port: 8082

spring:
  redis:
    database: 0
    host: localhost
    password:
    timeout: 3000
    jedis:
      pool:
        max-active: 5
        min-idle: 0
        max-wait: 1
        max-idle: 8
    port: 6379

security:
 oauth2:
  resource:
    filter-order: 3
 basic:
   enabled: false